# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db977211644df1bdc4bcbb26b18edc53a422c696e146c7137cf6a88b002caae071f797658e77cd41f7ba691608987b36156d2d73af8af532bdf5316d9ccfec6

test:
  secret_key_base: 785e23ae08b4f8e8fea0ecfc571851c38d07836a08626001b5d86611e4c808c648fcc86bf5638b992ef17958f33c58fe4fc7ac0060fcc5d90eec1d76153ad712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
